### ISSUE TITLE
"Smart dash" in code snippets

### ISSUE THREAD

**Issue by vi** [floooh/floooh.github.io#1]
Github Pages (or something else?) seem to convert `--` to `–`.

For example, in [asmjs diet](https://floooh.github.io/2016/08/27/asmjs-diet.html) article I see
`–closure 1`

While it should be (and I see in [the rendered source](https://github.com/floooh/floooh.github.io/blob/master/_posts/2016-08-27-asmjs-diet.md))
`--closure 1`

Maybe better enclose everything that might be copy-and-pasted into console in ``?

**Comment by floooh** [comment]
Whoops good catch, I'll see if I can fix that in the evening.
